#include "FFGLSDK.h"

#include "ffgl/FFGL.cpp"
#include "ffgl/FFGLPluginInfo.cpp"
#include "ffgl/FFGLPluginInfoData.cpp"
#include "ffgl/FFGLPluginManager.cpp"
#include "ffgl/FFGLPluginSDK.cpp"
#include "ffgl/FFGLThumbnailInfo.cpp"

#include "ffglex/FFGLFBO.cpp"
#include "ffglex/FFGLScopedBufferBinding.cpp"
#include "ffglex/FFGLScopedFBOBinding.cpp"
#include "ffglex/FFGLScopedRenderBufferBinding.cpp"
#include "ffglex/FFGLScopedSamplerActivation.cpp"
#include "ffglex/FFGLScopedShaderBinding.cpp"
#include "ffglex/FFGLScopedTextureBinding.cpp"
#include "ffglex/FFGLScopedVAOBinding.cpp"
#include "ffglex/FFGLScreenQuad.cpp"
#include "ffglex/FFGLShader.cpp"
#include "ffglex/FFGLUtilities.cpp"

#include "ffglquickstart/FFGLAudio.cpp"
#include "ffglquickstart/FFGLEffect.cpp"
#include "ffglquickstart/FFGLMixer.cpp"
#include "ffglquickstart/FFGLParam.cpp"
#include "ffglquickstart/FFGLParamBool.cpp"
#include "ffglquickstart/FFGLParamEvent.cpp"
#include "ffglquickstart/FFGLParamFFT.cpp"
#include "ffglquickstart/FFGLParamOption.cpp"
#include "ffglquickstart/FFGLParamRange.cpp"
#include "ffglquickstart/FFGLParamText.cpp"
#include "ffglquickstart/FFGLParamTrigger.cpp"
#include "ffglquickstart/FFGLPlugin.cpp"
#include "ffglquickstart/FFGLRandom.cpp"
#include "ffglquickstart/FFGLSmoothValue.cpp"
#include "ffglquickstart/FFGLSource.cpp"

#include "glsdk_0_5_2/glload/source/gl_load.c"